title: [Jan Gurgul - CV]
description: [Moje wykształcenie, zdolności, umiejętności i posiadana wiedza]
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
